### PR TITLE
Add support for Django 2.0, drop support for Django 1.4 to 1.7

### PR DESCRIPTION
**Pull request by saurabh-fueled**

### CODE REVIEW

**Comment by theskumar** [comment]
@niwinz possible you can merge and release a new version? Thanks :)

**Comment by niwinz** [comment]
Yeah, thanks for the PR; I will bump the version in two weeks (i'm on my holidays, i can't do it right now, sorry)

**Comment by theskumar** [comment]
Thanks. :)

**Comment by niwinz** [comment]
Released as 0.10

**Comment by theskumar** [comment]
Woaha! Thanks 🎉

**Pull request merged**
