### PR TITLE
Add django 1.9 support

### PR DESCRIPTION
**Pull request by theskumar**
- remove unsed `django.utils.functional.memoize` (removed in django 1.9)
- update docs
- Fixed test failing for django_jinja (django > 1.8)

This requires a new release.

### CODE REVIEW

**Comment by theskumar** [comment]
@niwinz I'm not sure why the test run for a particular matrix even though they are excluded.

niwinz_django-sites_-_travis_ci

Have a look at travis [results](https://travis-ci.org/niwinz/django-sites/). I tried my best to fix the test runner for all the versions of Django while adding support for python 3.5.

**Comment by niwinz** [comment]
Don't worry, I'll fix them! Thanks for your time

**Comment by niwinz** [comment]
Now merged and 0.9 released.

**Comment by theskumar** [comment]
:heart:, Thanks!

**Pull request merged**
