### PR TITLE
Add support for Django 3.x

### PR DESCRIPTION
**Pull request by CuriousLearner**
Hi @niwinz 

I've added support for Django 3.x. Will it be possible for you to create a release on pypi?

### CODE REVIEW

**Comment by CuriousLearner** [comment]
This would close #13

**Comment by CuriousLearner** [comment]
Here is the result for the CI: https://travis-ci.org/github/CuriousLearner/django-sites

@niwinz

**Comment by theskumar** [comment]
@niwinz would it is be possible for you to make a new release of this project? Or let me know if I can help with that in any way.

**Comment by CuriousLearner** [comment]
Hi Andrey (@niwinz) 👋🏻 

Could you please take a look at this one? This should enable the use of django-sites on Django 3.x.

Please let me know if you need any help with maintaining this library. I can make the release on pypi if you can provide me access.

Many thanks!

**Comment by niwinz** [comment]
I'm no longer using django, and python. So I can gladly give access or transfer this repository to a new maintainer.

**Comment by CuriousLearner** [comment]
Thanks @niwinz 

Can you please provide me access on Github and PyPi?

I'm with the name @CuriousLearner  on both platforms (https://pypi.org/user/CuriousLearner/)

**Comment by CuriousLearner** [comment]
Hi @niwinz Andrey 👋🏻 

Can you please provide me access on Github and PyPi for this package? I'm with name @CuriousLearner on both platforms.

Many thanks!

**Comment by niwinz** [comment]
Done, thanks

**Comment by CuriousLearner** [comment]
Thanks a lot @niwinz !

**Comment by CuriousLearner** [comment]
Hi @niwinz 👋🏻 

Just need one small help. Can you enable GithubActions on this repo from settings tab, please?

I cannot access that tab so I've to ask you.

Thanks a ton!

**Comment by niwinz** [comment]
Hmm, seems they are enabled:
image

And already running:
image

**Comment by CuriousLearner** [comment]
Yes, they started working.

Thanks! I've released a new version on pypi: https://pypi.org/project/django-sites/0.11/

**Comment by niwinz** [comment]
awesome! thanks for getting this project alive \o/

**Pull request merged**
